name: Docker
on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and Push Docker Image
        run: |
          docker build . \
            --pull \
            --tag ghcr.io/msrd0/abuild-aarch64 \
            --build-arg JOBS=2 \
            --memory $(( 6500 * 1024 * 1024 ))
          
          docker login -u msrd0 -p "${{ secrets.GHCR_TOKEN }}" ghcr.io
          docker push ghcr.io/msrd0/abuild-aarch64
